environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
